version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: assessment
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  spring-app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/assessment
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
    ports:
      - "8888:8888"
    command: ["./gradlew","clean","test"]